"""rename department

Revision ID: 1ee464d5e47b
Revises: 174d1a0371e8
Create Date: 2025-05-26 10:58:10.047974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee464d5e47b'
down_revision = '174d1a0371e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('deparment', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('deparments', 'deparment')
    # ### end Alembic commands ###
